name: beast_pype
channels:
  - conda-forge
  - bioconda
dependencies:
  # For unit testing
  - conda-forge::pytest
  - conda-forge::pytest-xdist
  - conda-forge::psutil
  # BEAST istelf
  - bioconda::beast2
  # Python
  # beast2-xml has had the occaisonal issue with installation python 3.12
  # on some OSs. beast2-xml works on suggest python 3.10 sticking to python 3.10.
  - conda-forge::python<3.11
  # Python Bioinformatics
  - conda-forge::biopython
  - bioconda::iqtree
  - bioconda::treetime
  - bioconda::seqkit
  - conda-forge::ete3
  # Python Data Sci
  - conda-forge::scipy
  - conda-forge::numpy
  - conda-forge::pandas
  # Plotting figures.
  - conda-forge::seaborn
  - conda-forge::matplotlib
  # MCMC diagnostics_of_selection
  - conda-forge::arviz
  - conda-forge::xarray
  # Utils
  - conda-forge::click
  - conda-forge::pyyaml
  - conda-forge::parallel
  # Jupyter & Jutyper based workflow
  - conda-forge::jupyter
  - conda-forge::papermill
  - conda-forge::nbconvert
  - conda-forge::nbformat
  - conda-forge::ipywidgets
  - conda-forge::bash_kernel
  - conda-forge::ipykernel
  # For packges on pip:
  - conda-forge::pip
  - pip: # Packages on pip:
      - beast2-xml>=1.4.1
      - dark-matter
      - python-dateutil
      - beast-pype
